POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "test name",
    "password": "test password"
}

###

POST http://localhost:3000/user/delete
Content-Type: application/json

{
    "name": "test name"
}
